### ISSUE TITLE
Are you open to contributions ?

### ISSUE THREAD

**Issue by MohamedLEGH** [makgyver/gossipy#3]
Hello,
I'm a PhD student at Sorbonne University and I've started to look at gossip learning. I've just discovered your simulator and I think I will use it for my work.
If I add new protocols or algorithms to the simulator, are you open that I add them to the project as pull requests ?

Thanks,
Mohamed Amine LEGHERABA

**Comment by ParsaMokhtariHessar** [comment]
this is my question too. after I'm done training my models I would like to contribute too! in the source code and I would like my paper to be added to the papers listed, that are implemented using gossipy. I would like to cite gossipy in my paper as my source code. would that be possible Mirko?

**Comment by makgyver** [comment]
Hi everyone, thank you for your interest in `gossipy`, and sorry for the delay.
You can contribute via the pull request mechanism. To cite this work, for now, simply use the GitHub link to the repository, and hopefully, soon there will be a paper about the library.

The papers cited in the README are not the ones using `gossipy` but the ones that I reproduced using it.

**Comment by makgyver** [comment]
Just FYI, I plan to expand the library with novel algorithms I find in the recent literature. So, if you have any suggestions, just let me know. Thanks.
