### ISSUE TITLE
Same code for Linear Regression and Logistic Regression ?

### ISSUE THREAD

**Issue by MohamedLEGH** [makgyver/gossipy#4]
Hello,
I'm new to machine learning but it seems to me that the implementation of Logistic Regression is the same as Linear Regression, it's simply a linear transformation: https://github.com/makgyver/gossipy/blob/main/gossipy/model/nn.py#L166

I would have suppose that we will have a sigmoid transformation, with the `torch.sigmoid` function, for example like in this tutorial : https://towardsdatascience.com/logistic-regression-with-pytorch-3c8bbea594be

Is it a bug or did I miss something ?

Thanks,
Mohamed

**Comment by makgyver** [comment]
Hi,
it is clearly a bug! thank you for spotting it. I will fix it soon.

**Comment by makgyver** [comment]
Fixed it!
