### ISSUE TITLE
Why use PyTorch for simple machine learning models (linear regression, logistic regression, ...) instead of scikit-learn ?

### ISSUE THREAD

**Issue by MohamedLEGH** [makgyver/gossipy#5]
Hello,
I was curious to know why you implement all the machine learning models in PyTorch instead of another library like scikit-learn ? Is it because it's easier to have all the models implemented in the same way ? Do you have plan to be compatible with other machine library in the future ?

Thanks,
Mohamed Amine

**Comment by makgyver** [comment]
Hi @MohamedLEGH, the main reason for implementing all of them in pytorch is convenience! In particular, the TorchModelHandler class can handle torch models regardless of the architecture. Clearly, if the merge or the update are not the standard ones they have to be changed (see AdaLine and Pegasos). I have no plans in making gossipy compatible with sklearn (or other libraries), however feel free to contribute to gossipy, if you like :)
