### ISSUE TITLE
Questions about the implementation of an algorithm

### ISSUE THREAD

**Issue by PhamAlexT** [makgyver/gossipy#6]
Hi,
First thank you for your good work.
I have a question regarding the class TorchModelPartition implemented here: https://github.com/makgyver/gossipy/blob/5ae94ab0025d12032e4af379a734601220eca489/gossipy/model/sampling.py#L110-L234

The method *_check* checks whether a tensor is of dimension 3 or more and *_partition* suppose that tensors are of dimension less or equal to 3 (as *_check* is called before). Why this limitation? It looks like the code of *_partition* can be extended to support tensors of dimension 4 but, maybe I am missing something?.
This current limitation prevents us to use LeNet-5 implemented here for example: https://github.com/lychengrex/LeNet-5-Implementation-Using-Pytorch/blob/master/LeNet-5%20Implementation%20Using%20Pytorch.ipynb

Sincerely,

**Comment by makgyver** [comment]
Hi @PhamAlexT, thank you for your interest in gossipy!
The limitation lies in the implementation of the `_partition` method that as of today can only handle up to 3D network layers. It can be "easily" extended to 4,5... etc by including specific cases. I am not sure if there is a convenient way to do a generic implementation for any dimension.
